### PR TITLE
Use sentry-cli for uploading instead of curl or rest client

### LINKED ISSUE #6: Plugin does not Batch Correctly
The plugin currently disregards the upfront checksum check and uploads zip files above the permitted size.

This come up in the forums: https://forum.sentry.io/t/cannot-upload-ios-dsym-file-error-413-entity-too-large/707

Correct behavior is

* check for each individual dsym file upfront if it needs uploading with the checksum endpoint
* re-compress files that are missing into zip files below the maximum size
* upload in multiple batches

### PR DESCRIPTION
**Pull request by HazAT**
Fixes  #6

### CODE REVIEW

**Comment by HazAT** [comment]
If we get this https://github.com/getsentry/sentry-cli/pull/34 merged and release version `0.24.0` we can merge this PR which greatly simplifies this gem because all the logic has been moved to `sentry-cli`.

Also we need a brew tap for `sentry-cli`

**Comment by HazAT** [comment]
`sentry-cli` will not be in the brew master repo but updated the error messages accordingly to show the sentry taps.

**Comment by HazAT** [comment]
@mitsuhiko @joshdholtz Any concerns merging this? It's a breaking change but since its harder to maintain 2 libs with all the new features we should go with using `sentry-cli` only.

**Comment by JagCesar** [comment]
Not sure I understand, but does this mean we should stop using the fastlane plugin in favour for the CLI?

We ran into the bug where dSYMs can't be uploaded due to size, which led me to this PR.

**Comment by mitsuhiko** [comment]
The plugin uses the `sentry-cli` client internally now.

**Comment by HazAT** [comment]
Please update to the latest version of the plugin, it will guide you through the process by installing in with homebrew.

**Comment by JagCesar** [comment]
Ok great. Our CI is currently running `v0.1.2`. Will update the plugin and install your cli on it then.

**Comment by HazAT** [comment]
Guys ... please upgrade to `1.0.2` the bug has been fixed.
The default parameter was pointing to an old sentry endpoint and the returned error wasn't that helpful.
It works now, promised 💯 😅

**Pull request merged**
